defaults: &defaults
  create_account_request:
    code: "01"
    params:
      Address: [C, 120]
      InstReprIDCode: [C, 30]
      InstReprIDType: [C, 1]
      InstReprName: [C, 20]
      AppSheetSerialNo: [A, 24]
      CertificateType: [C, 1]
      CertificateNo: [C, 30]
      InvestorName: [C, 120]
      TransactionDate: [A, 8]
      TransactionTime: [A, 6]
      IndividualOrInstitution: [A, 1]
      PostCode: [A, 6]
      TransactorCertNo: [C, 30]
      TransactorCertType: [C, 1]
      TransactorName: [C, 20]
      TransactionAccountID: [A, 17]
      DistributorCode: [C, 9]
      BusinessCode: [A, 3]
      AcctNoOfFMInClearingAgency: [C, 28]
      AcctNameOfFMInClearingAgency: [C, 60]
      ClearingAgencyCode: [A, 9]
      InvestorsBirthday: [A, 8]
      DepositAcct: [C, 19]
      RegionCode: [A, 4]
      EducationLevel: [C, 3]
      EmailAddress: [C, 40]
      FaxNo: [C, 24]
      VocationCode: [C, 3]
      HomeTelNo: [C, 22]
      AnnualIncome: [N, 8]
      MobileTelNo: [C, 24]
      BranchCode: [C, 9]
      OfficeTelNo: [C, 22]
      AccountAbbr: [C, 12]
      ConfidentialDocumentCode: [C, 8]
      Sex: [A, 1]
      SHSecuritiesAccountID: [C, 10]
      SZSecuritiesAccountID: [C, 10]
      TAAccountID: [C, 12]
      TelNo: [C, 22]
      TradingMethod: [C, 8]
      MinorFlag: [C, 1]
      DeliverType: [C, 1]
      TransactorIDType: [C, 1]
      AccountCardID: [C, 8]
      MultiAcctFlag: [A, 1]
      TargetTransactionAccountID: [A, 17]
      AcctNameOfInvestorInClearingAgency: [C, 60]
      AcctNoOfInvestorInClearingAgency: [C, 28]
      ClearingAgency: [A, 9]
      DeliverWay: [C, 8]
      Nationality: [C, 3]
      NetNo: [C, 9]
      Broker: [C, 12]
      CorpName: [C, 40]
      CertValidDate: [A, 8]
      InstTranCertValidDate: [A, 8]
      InstReprCertValidDate: [A, 8]
      ClientRiskRate: [C, 1]
      InstReprManageRange: [C, 2]
      ControlHolder: [C, 80]
      ActualController: [C, 80]
      MarriageStatus: [C, 1]
      FamilyNum: [N, 2]
      Penates: [N, 16, 2]
      MediaHobby: [C, 1]
      InstitutionType: [C, 1]
      EnglishFirstName: [C, 20]
      EnglishFamliyName: [C, 20]
      Vocation: [C, 4]
      CorpoProperty: [C, 2]
      StaffNum: [N, 16, 2]
      Hobbytype: [C, 2]
      Province: [C, 6]
      City: [C, 6]
      County: [C, 6]
      CommendPerson: [C, 40]
      CommendPersonType: [C, 1]
      AcceptMethod: [C, 1]
      FrozenCause: [A, 1]
      FreezingDeadline: [A, 8]
      OriginalSerialNo: [A, 20]
      OriginalAppSheetNo: [A, 24]

  create_account_response:
    code: "02"
    params:
      AppSheetSerialNo: [A, 24]
      TransactionCfmDate: [A, 8]
      ReturnCode: [A, 4]
      TransactionAccountID: [A, 17]
      DistributorCode: [C, 9]
      BusinessCode: [A, 3]
      TAAccountID: [A, 12]
      MultiAcctFlag: [A, 1]
      TASerialNO: [A, 20]
      TransactionDate: [A, 8]
      Transactiontime: [A, 6] #大小写有问题
      BranchCode: [C, 9]
      FromTAFlag: [A, 1]
      CertificateType: [C, 1]
      CertificateNo: [C, 30]
      InvestorName: [C, 120]
      IndividualOrInstitution: [A, 1]
      AccountAbbr: [C, 12]
      AccountCardID: [C, 8]
      RegionCode: [A, 4]
      TargetTransactionAccountID: [A, 17]
      NetNo: [C, 9]
      Specification: [C, 60]
      CustomerNo: [C, 12]
      FrozenCause: [A, 1]
      FreezingDeadline: [A, 8]
      ErrorDetail: [C, 60]
      BusinessCode: [A, 3]

  trade_request:
    code: "03"
    params:
      AppSheetSerialNo: [A, 24]
      FundCode: [C, 6]
      LargeRedemptionFlag: [A, 1]
      TransactionDate: [A, 8]
      TransactionTime: [A, 6]
      TransactionAccountID: [A, 17]
      DistributorCode: [C, 9]
      ApplicationVol: [N, 16, 2]
      ApplicationAmount: [N, 16, 2]
      BusinessCode: [A, 3]
      TAAccountID: [A, 12]
      DiscountRateOfCommission: [N, 5, 4]
      DepositAcct: [C, 19]
      RegionCode: [A, 4]
      CurrencyType: [A, 3]
      BranchCode: [C, 9]
      OriginalAppSheetNo: [A, 24]
      OriginalSubsDate: [A, 8]
      IndividualOrInstitution: [A, 1]
      ValidPeriod: [N, 2]
      DaysRedemptionInAdvance: [N, 5]
      RedemptionDateInAdvance: [A, 8]
      OriginalSerialNo: [A, 20]
      DateOfPeriodicSubs: [A, 8]
      TASerialNO: [A, 20]
      TermOfPeriodicSubs: [N, 5]
      FutureBuyDate: [A, 8]
      TargetDistributorCode: [C, 9]
      Charge: [N, 10, 2]
      TargetBranchCode: [C, 9]
      TargetTransactionAccountID: [A, 18]
      TargetRegionCode: [A, 4]
      DividendRatio: [N, 16, 2]
      Specification: [C, 60]
      CodeOfTargetFund: [A, 6]
      TotalBackendLoad: [N, 16, 2]
      ShareClass: [C, 1]
      OriginalCfmDate: [A, 8]
      DetailFlag: [C, 1]
      OriginalAppDate: [A, 8]
      DefDividendMethod: [A, 1]
      FrozenCause: [A, 1]
      FreezingDeadline: [A, 8]
      VarietyCodeOfPeriodicSubs: [C, 5]
      SerialNoOfPeriodicSubs: [C, 5]
      RationType: [C, 1]
      TargetTAAccountID: [C, 12]
      TargetRegistrarCode: [C, 2]
      NetNo: [C, 9]
      CustomerNo: [C, 12]
      TargetShareType: [C, 1]
      RationProtocolNo: [C, 20]
      BeginDateOfPeriodicSubs: [A, 8]
      EndDateOfPeriodicSubs: [A, 8]
      SendDayOfPeriodicSubs: [N, 2]
      Broker: [C, 12]
      SalesPromotion: [C, 3]
      AcceptMethod: [C, 1]
      ForceRedemptionType: [C, 1]
      TakeIncomeFlag: [C, 1]
      PurposeOfPeSubs: [C, 40]
      FrequencyOfPeSubs: [N, 5]
      PeriodSubTimeUnit: [C, 1]
      BatchNumOfPeSubs: [N, 16, 2]
      CapitalMode: [C, 2]
      DetailCapticalMode: [C, 2]
      BackenloadDiscount: [N, 5, 4]
      CombineNum: [C, 6]
      FutureSubscribeDate: [A, 8]
      TradingMethod: [C, 8]
      LargeBuyFlag: [A, 1]
      ChargeType: [C, 1]
      SpecifyRateFee: [N, 9, 8]
      SpecifyFee: [N, 16, 2]

  trade_response:
    code: "04"
    params:
      AppSheetSerialNo: [A, 24]
      TransactionCfmDate: [A, 8]
      CurrencyType: [A, 3]
      ConfirmedVol: [A, 16, 2]
      ConfirmedAmount: [A, 16, 2]
      FundCode: [C, 6]
      LargeRedemptionFlag: [A, 1]
      TransactionDate: [A, 8]
      Transactiontime: [A, 6] # 大小写有问题
      ReturnCode: [A, 4]
      TransactionAccountID: [A, 17]
      DistributorCode: [C, 9]
      ApplicationVol: [N, 16, 2]
      ApplicationAmount: [N, 16, 2]
      BusinessCode: [A, 3]
      TAAccountID: [A, 12]
      TASerialNO: [A, 20]
      BusinessFinishFlag: [C, 1]
      DiscountRateOfCommission: [N, 5, 4]
      DepositAcct: [C, 19]
      RegionCode: [A, 4]
      DownLoadDate: [A, 8] # 大小写有问题
      Charge: [N, 10, 2]
      AgencyFee: [N, 10, 2]
      NAV: [N, 7, 4]
      BranchCode: [C, 9]
      OriginalAppSheetNo: [A, 24]
      OriginalSubsDate: [A, 8]
      OtherFee1: [N, 10, 2]
      IndividualOrInstitution: [A, 1]
      RedemptionDateInAdvance: [A, 8]
      StampDuty: [N, 16, 2]
      ValidPeriod: [N, 2]
      RateFee: [N, 9, 8]
      TotalBackendLoad: [N, 16, 2]
      OriginalSerialNo: [A, 20]
      Specification: [C, 60]
      DateOfPeriodicSubs: [A, 8]
      TargetDistributorCode: [C, 9]
      TargetBranchCode: [C, 9]
      TargetTransactionAccountID: [A, 18]
      TargetRegionCode: [A, 4]
      TransferDirection: [A, 1]
      DefDividendMethod: [A, 1]
      DividendRatio: [N, 16, 2]
      Interest: [N, 10, 2]
      VolumeByInterest: [N, 10, 2]
      InterestTax: [N, 16, 2]
      TradingPrice: [N, 7, 4]
      FreezingDeadline: [A, 8]
      FrozenCause: [A, 1]
      Tax: [N, 16, 2]
      TargetNAV: [N, 7, 4]
      TargetFundPrice: [N, 7, 4]
      CfmVolOfTargetFund: [N, 16, 2]
      MinFee: [N, 10, 2]
      OtherFee2: [N, 16, 2]
      OriginalAppDate: [A, 8]
      TransferFee: [N, 10, 2]
      FromTAFlag: [A, 1]
      ShareClass: [C, 1]
      DetailFlag: [C, 1]
      RedemptionInAdvanceFlag: [A, 1]
      FrozenMethod: [A, 1]
      OriginalCfmDate: [A, 8]
      RedemptionReason: [A, 1]
      CodeOfTargetFund: [A, 6]
      TotalTransFee: [N, 10, 2]
      VarietyCodeOfPeriodicSubs: [C, 5]
      SerialNoOfPeriodicSubs: [C, 5]
      RationType: [C, 1]
      TargetTAAccountID: [C, 12]
      TargetRegistrarCode: [C, 2]
      NetNo: [C, 9]
      CustomerNo: [C, 12]
      TargetShareType: [C, 1]
      RationProtocolNo: [C, 20]
      BeginDateOfPeriodicSubs: [A, 8]
      EndDateOfPeriodicSubs: [A, 8]
      SendDayOfPeriodicSubs: [N, 2]
      Broker: [C, 12]
      SalesPromotion: [C, 3]
      AcceptMethod: [C, 1]
      ForceRedemptionType: [C, 1]
      AlternationDate: [A, 8]
      TakeIncomeFlag: [C, 1]
      PurposeOfPeSubs: [C, 40]
      FrequencyOfPeSubs: [N, 5]
      PeriodSubTimeUnit: [C, 1]
      BatchNumOfPeSubs: [N, 16, 2]
      CapitalMode: [C, 2]
      DetailCapticalMode: [C, 2]
      BackenloadDiscount: [N, 5, 4]
      CombineNum: [C, 6]
      RefundAmount: [N, 16, 2]
      SalePercent: [N, 8, 5]
      ManagerRealRatio: [N, 7, 4]
      ChangeFee: [N, 16, 2]
      RecuperateFee: [N, 16, 2]
      AchievementPay: [N, 16, 2]
      AchievementCompen: [N, 16, 2]
      SharesAdjustmentFlag: [C, 1]
      GeneralTASerialNO: [A, 20]
      UndistributeMonetaryIncome: [N, 16, 2]
      UndistributeMonetaryIncomeFlag: [C, 1]
      BreachFee: [N, 16, 2]
      BreachFeeBackToFund: [N, 16, 2]
      PunishFee: [N, 16, 2]
      TradingMethod: [C, 8]
      ChangeAgencyFee: [N, 16, 2]
      RecuperateAgencyFee: [N, 16, 2]
      ErrorDetail: [C, 60]
      LargeBuyFlag: [A, 1]
      RaiseInterest: [N, 16, 2]
      FeeCalculator: [A, 1]
      ShareRegisterDate: [A, 8]

  asset_file:
    code: "05"
    params:
      AvailableVol: [N, 16, 2]
      TotalVolOfDistributorInTA: [N, 16, 2]
      TransactionCfmDate: [A, 8]
      FundCode: [C, 6]
      TransactionAccountID: [A, 17]
      DistributorCode: [C, 9]
      TAAccountID: [C, 12]
      TotalFrozenVol: [N, 16, 2]
      BranchCode: [C, 9]
      TASerialNO: [A, 20]
      TotalBackendLoad: [N, 16, 2]
      ShareClass: [A, 1]
      DetailFlag: [A, 1]
      AccountStatus: [A, 1]
      ShareRegisterDate: [A, 8]
      UndistributeMonetaryIncome: [N, 16, 2]
      UndistributeMonetaryIncomeFlag: [C, 1]
      GuaranteedAmount: [N, 16, 2]
      SourceType: [C, 1]
      DefDividendMethod: [A, 1]

  gain_file:
    code: "07"
    params:
      FundName: [C, 40]
      TotalFundVol: [N, 16, 2]
      FundCode: [C, 6]
      FundStatus: [C, 1]
      NAV: [N, 7, 4]
      UpdateDate: [A, 8]
      NetValueType: [C, 1]
      AccumulativeNAV: [N, 7, 4]
      ConvertStatus: [C, 1]
      PeriodicStatus: [C, 1]
      TransferAgencyStatus: [C, 1]
      FundSize: [N, 16, 2]
      CurrencyType: [A, 3]
      AnnouncFlag: [C, 1]
      DefDividendMethod: [A, 1]
      InstAppSubsAmnt: [N, 16, 2]
      InstAppSubsVol: [N, 16, 2]
      MinAmountByInst: [N, 16, 2]
      MinVolByInst: [N, 16, 2]
      CustodianCode: [A, 3]
      AmountOfPeriodicSubs: [N, 16, 2]
      DateOfPeriodicSubs: [A, 8]
      MaxRedemptionVol: [N, 16, 2]
      MinAccountBalance: [N, 16, 2]
      IPOStartDate: [A, 8]
      IPOEndDate: [A, 8]
      FundManagerCode: [C, 3]
      IndiAppSubsVol: [N, 16, 2]
      IndiAppSubsAmount: [N, 16, 2]
      MinSubsVolByIndi: [N, 16, 2]
      MinSubsAmountByIndi: [N, 16, 2]
      RegistrarCode: [C, 2]
      FundSponsor: [A, 3]
      TradingPrice: [N, 7, 4]
      FaceValue: [N, 7, 4]
      DividentDate: [A, 8]
      RegistrationDate: [A, 8]
      XRDate: [A, 8]
      MaxSubsVolByIndi: [N, 16, 2]
      MaxSubsAmountByIndi: [N, 16, 2]
      MaxSubsVolByInst: [N, 16, 2]
      MaxSubsAmountByInst: [N, 16, 2]
      UnitSubsVolByIndi: [N, 16, 2]
      UnitSubsAmountByIndi: [N, 16, 2]
      UnitSubsVolByInst: [N, 16, 2]
      UnitSubsAmountByInst: [N, 16, 2]
      MinBidsAmountByIndi: [N, 16, 2]
      MinBidsAmountByInst: [N, 16, 2]
      MinAppBidsAmountByIndi: [N, 16, 2]
      MinAppBidsAmountByInst: [N, 16, 2]
      MinRedemptionVol: [N, 16, 2]
      MinInterconvertVol: [N, 16, 2]
      IssueTypeByIndi: [C, 1]
      IssueTypeByInst: [C, 1]
      SubsType: [C, 1]
      CollectFeeType: [C, 1]
      NextTradeDate: [A, 8]
      ValueLine: [N, 7, 2]
      TotalDivident: [N, 8, 5]
      FundIncome: [N, 8, 5]
      FundIncomeFlag: [C, 1]
      Yield: [N, 8, 5]
      YieldFlag: [C, 1]
      GuaranteedNAV: [N, 7, 4]
      FundYearIncomeRate: [N, 8, 5]
      FundYearIncomeRateFlag: [C, 1]
      IndiMaxPurchase: [N, 16, 2]
      InstMaxPurchase: [N, 16, 2]
      IndiDayMaxSumBuy: [N, 16, 2]
      InstDayMaxSumBuy: [N, 16, 2]
      IndiDayMaxSumRedeem: [N, 16, 2]
      InstDayMaxSumRedeem: [N, 16, 2]
      IndiMaxRedeem: [N, 16, 2]
      InstMaxRedeem: [N, 16, 2]
      FundDayIncomeFlag: [C, 1]
      FundDayIncome: [N, 16, 2]
      AllowBreachRedempt: [C, 1]
      FundType: [C, 2]
      FundTypeName: [C, 30]
      RegistrarName: [C, 40]
      FundManagerName: [C, 40]
      FundServerTel: [C, 30]
      FundInternetAddress: [C, 40]




development:
  <<: *defaults

production:
  <<: *defaults