defaults: &defaults
  create_account_request:
    code: "01"
    params:
      Address: [C, 120]
      InstReprIDCode: [C, 30]
      InstReprIDType: [C, 1]
      InstReprName: [C, 20]
      AppSheetSerialNo: [A, 24]
      CertificateType: [C, 1]
      CertificateNo: [C, 30]
      InvestorName: [C, 120]
      TransactionDate: [A, 8]
      TransactionTime: [A, 6]
      IndividualOrInstitution: [A, 1]
      PostCode: [A, 6]
      TransactorCertNo: [C, 30]
      TransactorCertType: [C, 1]
      TransactorName: [C, 20]
      TransactionAccountID: [A, 17]
      DistributorCode: [C, 9]
      BusinessCode: [A, 3]
      AcctNoOfFMInClearingAgency: [C, 28]
      AcctNameOfFMInClearingAgency: [C, 60]
      ClearingAgencyCode: [A, 9]
      InvestorsBirthday: [A, 8]
      DepositAcct: [C, 19]
      RegionCode: [A, 4]
      EducationLevel: [C, 3]
      EmailAddress: [C, 40]
      FaxNo: [C, 24]
      VocationCode: [C, 3]
      HomeTelNo: [C, 22]
      AnnualIncome: [N, 8]
      MobileTelNo: [C, 24]
      BranchCode: [C, 9]
      OfficeTelNo: [C, 22]
      AccountAbbr: [C, 12]
      ConfidentialDocumentCode: [C, 8]
      Sex: [A, 1]
      SHSecuritiesAccountID: [C, 10]
      SZSecuritiesAccountID: [C, 10]
      TAAccountID: [C, 12]
      TelNo: [C, 22]
      TradingMethod: [C, 8]
      MinorFlag: [C, 1]
      DeliverType: [C, 1]
      TransactorIDType: [C, 1]
      AccountCardID: [C, 8]
      MultiAcctFlag: [A, 1]
      TargetTransactionAccountID: [A, 17]
      AcctNameOfInvestorInClearingAgency: [C, 60]
      AcctNoOfInvestorInClearingAgency: [C, 28]
      ClearingAgency: [A, 9]
      DeliverWay: [C, 8]
      Nationality: [C, 3]
      NetNo: [C, 9]
      Broker: [C, 12]
      CorpName: [C, 40]
      CertValidDate: [A, 8]
      InstTranCertValidDate: [A, 8]
      InstReprCertValidDate: [A, 8]
      ClientRiskRate: [C, 1]
      InstReprManageRange: [C, 2]
      ControlHolder: [C, 80]
      ActualController: [C, 80]
      MarriageStatus: [C, 1]
      FamilyNum: [N, 2]
      Penates: [N, 16, 2]
      MediaHobby: [C, 1]
      InstitutionType: [C, 1]
      EnglishFirstName: [C, 20]
      EnglishFamliyName: [C, 20]
      Vocation: [C, 4]
      CorpoProperty: [C, 2]
      StaffNum: [N, 16, 2]
      Hobbytype: [C, 2]
      Province: [C, 6]
      City: [C, 6]
      County: [C, 6]
      CommendPerson: [C, 40]
      CommendPersonType: [C, 1]
      AcceptMethod: [C, 1]
      FrozenCause: [A, 1]
      FreezingDeadline: [A, 8]
      OriginalSerialNo: [A, 20]
      OriginalAppSheetNo: [A, 24]

development:
  <<: *defaults

production:
  <<: *defaults